// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxiKqcSk5BA_l5k7T-aTdBKHxnOJ-deMQ',
    appId: '1:84043750399:web:fee61b0bfb74aba788e5ca',
    messagingSenderId: '84043750399',
    projectId: 'attendanceapp-4f43c',
    authDomain: 'attendanceapp-4f43c.firebaseapp.com',
    storageBucket: 'attendanceapp-4f43c.firebasestorage.app',
    measurementId: 'G-VH4XS8KYZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdhOwLBz3QZRiFFQU5NOQZOS2HaknUg6s',
    appId: '1:84043750399:android:3effc0d234a6539a88e5ca',
    messagingSenderId: '84043750399',
    projectId: 'attendanceapp-4f43c',
    storageBucket: 'attendanceapp-4f43c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGztIp3H_18TUQc0LoLM9Zs1_iTGgeRPI',
    appId: '1:84043750399:ios:9c5cc5963db3816488e5ca',
    messagingSenderId: '84043750399',
    projectId: 'attendanceapp-4f43c',
    storageBucket: 'attendanceapp-4f43c.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGztIp3H_18TUQc0LoLM9Zs1_iTGgeRPI',
    appId: '1:84043750399:ios:9c5cc5963db3816488e5ca',
    messagingSenderId: '84043750399',
    projectId: 'attendanceapp-4f43c',
    storageBucket: 'attendanceapp-4f43c.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxiKqcSk5BA_l5k7T-aTdBKHxnOJ-deMQ',
    appId: '1:84043750399:web:0b1611d7628c172388e5ca',
    messagingSenderId: '84043750399',
    projectId: 'attendanceapp-4f43c',
    authDomain: 'attendanceapp-4f43c.firebaseapp.com',
    storageBucket: 'attendanceapp-4f43c.firebasestorage.app',
    measurementId: 'G-SRZ321SFW0',
  );
}
